name: Build

on:
  pull_request:
  push:
    branches: "**"

env:
  OBSIDIAN_VERSION: "1.1.16"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Obsidian
        run: |
          wget -q https://github.com/obsidianmd/obsidian-releases/releases/download/v$OBSIDIAN_VERSION/Obsidian-$OBSIDIAN_VERSION-universal.dmg
          sudo hdiutil attach Obsidian-$OBSIDIAN_VERSION-universal.dmg
          sudo cp -rf "/Volumes/Obsidian $OBSIDIAN_VERSION-universal/Obsidian.app" /Applications
          sudo hdiutil detach "/Volumes/Obsidian $OBSIDIAN_VERSION-universal"
      - name: Lint
        run: npm run lint
      - name: Test
        run: |
          npm run build-with-tests
          npm test
